Upgrading xstream version & whitelisting classes for deserialization
marklogic/marklogic-contentpump pull request #217
Opened 2022-01-28 02:26 UTC by abika5

2022-01-28 18:44 UTC, yunzvanessa commented on src/main/java/com/marklogic/contentpump/DocumentMetadata.java
> +        xstream.allowTypes(new Class[] {com.marklogic.contentpump.DocumentMetadata.class});
The parameter that is passed to allowTypes() is an array of classes. So I think you can combine those two lines.

2022-01-28 18:44 UTC, yunzvanessa requested changes
The parameter that is passed to allowTypes() is an array of classes. So I think you can combine those two lines.

2022-01-28 22:15 UTC, abika5 commented
I will create a new PR.

2022-01-28 22:18 UTC, yunzvanessa commented
Hi Abika,

You do not need to create a new PR. Just make new commits to your personal branch and the new commits will be reflected here, and it will keep track of all the commit history.

2022-01-28 22:22 UTC, abika5 commented
Made the changes suggested

2022-01-28 22:32 UTC, yunzvanessa commented
Hi Abika,

If you haven't, please make sure to build mlcp and run unit tests again before I approve it, to prevent typos/errors etc.

Thanks,
Vanessa

2022-01-28 22:33 UTC, abika5 commented
Sure vanessa, will do now

2022-01-28 23:05 UTC, abika5 commented
Unit testing passed on local.

2022-01-29 00:09 UTC, yunzvanessa approved these changes
Looks good. Thanks!

2022-02-02 19:02 UTC, merged